### ISSUE TITLE
Sidebar Actions missing?

### ISSUE THREAD

**Issue by Padrone56** [loremaps/LoreMaps#1]
The code doesn't seem to have the Sidebar Actions as the website does. Does git contain the latest code for the website?

**Comment by loremaps** [comment]
@Padrone56 as discussed via email:

Sidebar leaflet plugin is loaded at line 113:
https://github.com/loremaps/LoreMaps/blob/82b0cb11cb2ca81e07cf4082a770e97cf669a0c6/src/RpgCartography/Views/Shared/_Layout.cshtml#L113

`fantasyMap.js` is loaded at line 132:
https://github.com/loremaps/LoreMaps/blob/82b0cb11cb2ca81e07cf4082a770e97cf669a0c6/src/RpgCartography/Views/Shared/_Layout.cshtml#L132

Please check the network tab in the developer tools that Sidebar plugin ("L.Control.Sidebar.js") is loaded.

Since we had this discussion quite some time ago, I will close this issue. If you need further help, you can comment to the closed topic, and i will try to check this out.
